#!/usr/bin/env python3

from rich import print
import argparse
import toposort

from exploit.task import Task
from exploit.instruction import Assign, Add, Sub
from exploit.system import System, Sequential, Parallelize
from exploit.variable import Variable

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--view', '-v', action='store_true', help='View the graph(s).')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    try:
        t1 = Task([
            Assign('x', 10)
        ])
        t2 = Task([
            Assign('x', 1)
        ], dependencies=t1)
        t3 = Task([
            Assign('z', 1)
        ], dependencies=t1)
        t4 = Task([
            Assign('y', 15)
        ], dependencies=[t2])
        t5 = Task([
            Assign('r', 10)
        ], dependencies=t3)
        t6 = Task([
            Add('x', 'y', 'z')
        ], dependencies=[t4, t5])

        ##############################
        # Normal system
        ##############################
        s1 = System()
        s1.add_task(t1)
        s1.add_task(t2)
        s1.add_task(t3)
        s1.add_task(t4)
        s1.add_task(t5)
        s1.add_task(t6)
        s1.draw('graph1', view=args.view)
        s1.run()
        print(s1.get_memory_cells())

        t1 = Task([
            Assign('x', 1)
        ], name=1)
        s2 = System()
        s2.add_task(t1)
        s2.draw('graph2', view=args.view)
        s2.run()
        print(s2.get_memory_cells())

    except (RuntimeError, ValueError) as e:
        print('ERREUR :', e)
        print('ERREUR :', e.__doc__)

if __name__ == '__main__':
    main()